name: Bug Report
description: Reporte um problema no data-gen
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar! Preencha as informações abaixo para nos ajudar a resolver o problema.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist antes de reportar
      description: Verifique esses itens antes de abrir o bug report
      options:
        - label: Verifiquei se tenho Python 3.9+ instalado
        - label: Instalei as dependências com `pip install -e .` ou `uv pip install -e .`
        - label: Li o README e segui todos os passos
        - label: Busquei por issues similares e não encontrei

  - type: dropdown
    id: component
    attributes:
      label: Componente afetado
      description: Selecione o componente com problema
      options:
        - Generators (data_gen/generators/)
        - Kafka Sink (data_gen/sinks/kafka.py)
        - PostgreSQL Sink (data_gen/sinks/postgres.py)
        - CloudEvents Headers
        - Docker Compose / Infraestrutura
        - Scripts (load_data.py, etc.)
        - Outro
    validations:
      required: true

  - type: dropdown
    id: sink
    attributes:
      label: Tipo de sink
      description: Para onde está enviando os dados?
      options:
        - Kafka
        - PostgreSQL
        - Console / stdout
        - Outro
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      description: Qual o impacto do problema?
      options:
        - Bloqueante - Não consigo usar o data-gen
        - Alto - Funcionalidade importante não funciona
        - Médio - Funciona parcialmente ou com workaround
        - Baixo - Problema menor ou cosmético
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do problema
      description: Descreva o que aconteceu
      placeholder: |
        O que aconteceu?
        O que você esperava que acontecesse?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos exatos para reproduzir o problema
      placeholder: |
        1. Clone o repositório
        2. Execute `pip install -e .`
        3. Execute `python scripts/load_data.py --customers 10`
        4. ...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
      description: O que deveria acontecer?
      placeholder: Descreva o que você esperava que acontecesse
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs de erro
      description: Cole a mensagem de erro ou stack trace
      render: shell
      placeholder: |
        Cole aqui os logs ou erro...

  - type: textarea
    id: config
    attributes:
      label: Configuração utilizada
      description: Cole sua configuração (remova dados sensíveis)
      render: yaml
      placeholder: |
        # Comando utilizado
        python scripts/load_data.py --customers 10 --skip-postgres

        # Ou configuração do producer
        bootstrap.servers: localhost:9092
        ...

  - type: dropdown
    id: os
    attributes:
      label: Sistema Operacional
      options:
        - macOS (Intel)
        - macOS (Apple Silicon M1/M2/M3/M4)
        - Ubuntu / Debian
        - Windows 10
        - Windows 11
        - Outro Linux
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Versão do Python
      description: Output de `python --version`
      placeholder: "Python 3.11.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Informações adicionais
      description: Screenshots, tentativas de solução, ou qualquer outra informação relevante
      placeholder: |
        - Já tentei...
        - Notei que...
